version: '3'
services:
  apicurio-studio-auth:
    ports:
      - '7530:8443'
    env_file:
      - .env
    image: apicurio/apicurio-studio-auth
    environment:
      APICURIO_KEYCLOAK_USER: admin
      APICURIO_KEYCLOAK_PASSWORD: password123!
      APICURIO_UI_URL: ${APICURIO_UI_URL}

  apicurio-studio-db:
    env_file:
      - .env
    image: 'postgres:9.6'
    environment:
      POSTGRES_DB: ${AS_DATABASE}
      POSTGRES_USER: ${AS_DB_USER}
      POSTGRES_PASSWORD: ${AS_DB_PASSWORD}

  apicurio-studio-ws:
    env_file:
      - .env
    image: 'apicurio/apicurio-studio-ws:${APICURIO_WS_VERSION}'
    depends_on: [apicurio-studio-db]
    ports:
      - '7529:8443'
    environment:
      APICURIO_PORT_OFFSET: ${APICURIO_PORT_OFFSET}
      APICURIO_DB_DRIVER_NAME: ${APICURIO_DB_DRIVER_NAME}
      APICURIO_DB_CONNECTION_URL: ${APICURIO_DB_CONNECTION_URL}
      APICURIO_DB_USER_NAME: ${APICURIO_DB_USER_NAME}
      APICURIO_DB_PASSWORD: ${APICURIO_DB_PASSWORD}
      APICURIO_DB_INITIALIZE: ${APICURIO_DB_INITIALIZE}
      APICURIO_DB_TYPE: ${APICURIO_DB_TYPE}
      APICURIO_LOGGING_LEVEL: ${APICURIO_LOGGING_LEVEL}
      APICURIO_MIN_HEAP: ${APICURIO_MIN_HEAP}
      APICURIO_MAX_HEAP: ${APICURIO_MAX_HEAP}

  apicurio-studio-api:
    env_file:
      - .env
    image: 'apicurio/apicurio-studio-api:${APICURIO_API_VERSION}'
    depends_on: [apicurio-studio-db, apicurio-studio-ws]
    ports:
      - '7528:8443'
    environment:
      APICURIO_KC_AUTH_URL: ${APICURIO_KC_AUTH_URL}
      APICURIO_KC_REALM: ${APICURIO_KC_REALM}
      APICURIO_KC_CLIENT_ID: ${APICURIO_KC_CLIENT_ID}
      APICURIO_KC_SSL_REQUIRED: ${APICURIO_KC_SSL_REQUIRED}
      APICURIO_KC_DISABLE_TRUST_MANAGER: ${APICURIO_KC_DISABLE_TRUST_MANAGER}
      APICURIO_PORT_OFFSET: ${APICURIO_PORT_OFFSET}
      APICURIO_DB_DRIVER_NAME: ${APICURIO_DB_DRIVER_NAME}
      APICURIO_DB_CONNECTION_URL: ${APICURIO_DB_CONNECTION_URL}
      APICURIO_DB_USER_NAME: ${APICURIO_DB_USER_NAME}
      APICURIO_DB_PASSWORD: ${APICURIO_DB_PASSWORD}
      APICURIO_DB_INITIALIZE: ${APICURIO_DB_INITIALIZE}
      APICURIO_DB_TYPE: ${APICURIO_DB_TYPE}
      APICURIO_LOGGING_LEVEL: ${APICURIO_LOGGING_LEVEL}
      APICURIO_MIN_HEAP: ${APICURIO_MIN_HEAP}
      APICURIO_MAX_HEAP: ${APICURIO_MAX_HEAP}
      APICURIO_GITHUB_API_URL: ${APICURIO_GITHUB_API_URL}
      APICURIO_GITLAB_API_URL: ${APICURIO_GITLAB_API_URL}
      APICURIO_BITBUCKET_API_URL: ${APICURIO_BITBUCKET_API_URL}

  apicurio-studio-ui:
    env_file:
      - .env
    image: 'apicurio/apicurio-studio-ui:${APICURIO_UI_VERSION}'
    depends_on: [apicurio-studio-db, apicurio-studio-api, apicurio-studio-ws, apicurio-studio-auth]
    ports:
      - '7527:8443'
    environment:
      APICURIO_KC_AUTH_URL: ${APICURIO_KC_AUTH_URL}
      APICURIO_KC_REALM: ${APICURIO_KC_REALM}
      APICURIO_KC_CLIENT_ID: ${APICURIO_KC_CLIENT_ID}
      APICURIO_KC_SSL_REQUIRED: ${APICURIO_KC_SSL_REQUIRED}
      APICURIO_KC_DISABLE_TRUST_MANAGER: ${APICURIO_KC_DISABLE_TRUST_MANAGER}
      APICURIO_PORT_OFFSET: ${APICURIO_PORT_OFFSET}
      APICURIO_LOGGING_LEVEL: ${APICURIO_LOGGING_LEVEL}
      APICURIO_MIN_HEAP: ${APICURIO_MIN_HEAP}
      APICURIO_MAX_HEAP: ${APICURIO_MAX_HEAP}
      APICURIO_UI_HUB_API_URL: ${APICURIO_UI_HUB_API_URL}
      APICURIO_UI_EDITING_URL: ${APICURIO_UI_EDITING_URL}
